### ISSUE TITLE
Error deleting root disk

### ISSUE THREAD

**Issue by vunhan** [bizflycloud/terraform-provider-bizflycloud#17]
I got 400 bad request when tried to destroy a VM with their root disk, logs is in followed screenshot.
![image](https://user-images.githubusercontent.com/6767512/123753510-22a03580-d8e4-11eb-967c-5d8ec4f470cc.png)

**Comment by vunhan** [comment]
Thank you @greatbn

**Comment by greatbn** [comment]
@vunhan  thanks for your feedback. :D
