### ISSUE TITLE
Provision new kubernetes done but can't fetch the kubeconfig for at least 30 minutes

### ISSUE THREAD

**Issue by hung0913208** [bizflycloud/terraform-provider-bizflycloud#61]
Hi team,
Since my terraform repo is a bit complicated I would like to present the overall architecture and explain the issue instead, if you need troubleshooting with both source code, state file and resources, please ping me with email [hung.pham@alpaca.vn](mailto:hung.pham@alpaca.vn).

My team is using one VPC for internal traffic and build a kubernetes cluster with nodepool 4c_8g and storage type premium_hdd. We define kubernetes would be depended on the VPC module and we also put a resource time_sleep to make sure that the vpc would be start/destroy (the timeout is 10 seconds). I also build a null_resource to start after the kubernetes resource has started. This is a bash script could be seen at this ticket #60. Here is the log from my TF cloud, I have enabled the debug log for the bash script above.

> module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Destroying... [id=7249550077045709516]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Destruction complete after 0s
module.kubernetes.local_file.render_waiting_bizfly_kubernetes_available_script: Creating...
module.kubernetes.local_file.render_install_infrastructure_on_new_kubernetes_cluster_script: Creating...
module.kubernetes.local_file.render_waiting_bizfly_kubernetes_available_script: Creation complete after 0s [id=1afc87f0bb746b1985d612151df15b2b50f22692]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Creating...
module.kubernetes.local_file.render_install_infrastructure_on_new_kubernetes_cluster_script: Creation complete after 0s [id=85622a661ad5f15b00e45cc0b630433c5e4f9ef5]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Provisioning with 'local-exec'...
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): Executing: ["/usr/bin/bash" "kubernetes/waiting.sh"]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + /usr/bin/curl -LksS https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.12/bizflyctl_Linux_x86_64.tar.gz
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + /usr/bin/tar xvz
module.internal.bizflycloud_vpc_network.vpc_network[0]: Modifying... [id=9ae6dcaa-98d7-4e68-80df-3f25b56237b5]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): ++ /usr/bin/curl -L -s https://dl.k8s.io/release/stable.txt
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + /usr/bin/curl -LO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + chmod +x ./kubectl
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + chmod +x ./bizfly
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + export BIZFLY_CLOUD_EMAIL=***
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + BIZFLY_CLOUD_EMAIL=***
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + export BIZFLY_CLOUD_PASSWORD=***
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + BIZFLY_CLOUD_PASSWORD=***
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + export BIZFLY_CLOUD_REGION=HN
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + BIZFLY_CLOUD_REGION=HN
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + export BIZFLY_CLOUD_PROJECT_ID=***
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + BIZFLY_CLOUD_PROJECT_ID=***
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + for i in {0..30}
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + ./bizfly kubernetes kubeconfig get blc769oakot87q0h
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): ++ cat ./blc769oakot87q0h.kubeconfig
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): ++ wc -l
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): + [[ 19 -ne 0 ]]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): ++ ./kubectl --kubeconfig ./blc769oakot87q0h.kubeconfig get pods -A
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): ++ grep kube-system
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): ++ wc -l
module.internal.bizflycloud_vpc_network.vpc_network[0]: Modifications complete after 5s [id=9ae6dcaa-98d7-4e68-80df-3f25b56237b5]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [10s elapsed]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [20s elapsed]
**module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): E0115 04:47:36.840936     324 memcache.go:238] couldn't get current server API group list: Get "https://blc769oakot87q0h.api.hn.bke.bfcplatform.vn/api?timeout=32s": net/http: TLS handshake timeout - error from a previous attempt: EOF**
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [30s elapsed]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [40s elapsed]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): E0115 04:47:57.242780     324 memcache.go:238] couldn't get current server API group list: Get "https://blc769oakot87q0h.api.hn.bke.bfcplatform.vn/api?timeout=32s": net/http: TLS handshake timeout - error from a previous attempt: EOF
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [50s elapsed]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [1m0s elapsed]
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0] (local-exec): E0115 04:48:18.337721     324 memcache.go:238] couldn't get current server API group list: Get "https://blc769oakot87q0h.api.hn.bke.bfcplatform.vn/api?timeout=32s": EOF
module.kubernetes.null_resource.wait_until_bizfly_kubernetes_available[0]: Still creating... [1m10s elapsed]

As you can see, event if we could fetch the kubeconfig but we can't validate the cluster since we receive the issue TLS handshake timeout. Feel free to ping me with the email.

Thank you
Hung Pham

**Comment by pmint93** [comment]
@hung0913208 Thanks for reaching us and provide very detailed information.

The kubeconfig was fetched correctly. However the API server need time to bootstrap, and sometimes it take longer than expected (usually 5 minutes after creation).

In this case, your cluster taking more than 30 minutes to bootstrap was totally unacceptable. After investigation, we found that it related to etcd database slow provisioning.

To make sure clusters successfully provisioned, bootstrapped and healthy we suggest you do some check over the API endpoint before doing further.

Sorry for your bad experiences with us. We will continue doing our best to improve, and your feedbacks really helpful. 
Thanks !
